### ISSUE TITLE
How to sync specified table only?

### ISSUE THREAD

**Issue by stepbystep2** [go-mysql-org/go-mysql#687]
I have two dbs: `hospital` and `school`
In hospital I have a table: `department`
In school I have a table: `student`
I want to sync `student` only, so my `config.toml` like this:
```toml
addr = "127.0.0.1:3306"
user = "root"
password = "123"

[dump]
mysqldump = "mysqldump"
table_db = "school"
tables = [ "student" ]
```
My code like this:
```
func main() {
        cfg, err := canal.NewConfigWithFile("config.toml")
	if err != nil { panic(err) }
	cfg.ServerID = uint32(rand.New(rand.NewSource(time.Now().Unix())).Intn(1000)) + 1001
	c, err := canal.NewCanal(cfg)
	if err != nil {
		log.Fatal(err)
	}

	c.SetEventHandler(&MyEventHandler{})

	pos, err := c.GetMasterPos()
	if err != nil {
		panic(err)
	}

	err = c.RunFrom(pos)
	if err != nil {
		panic(err)
	}
}

func (h *MyEventHandler) OnRow(e *canal.RowsEvent) error {
	log.Printf("%s %v\n\n", e.Action, e.Rows)
}
```
But when I insert or delete some data in `department`, `OnRow` print
So, `table_db = "school" tables = [ "student" ]` in `config.toml` doesn't work,right?
How to sync specified table only?
Sorry, I am a noob
