### ISSUE TITLE
Can't connect to mysql server 8.0 when password is larger than 19 characters 

### ISSUE THREAD

**Issue by erfanium** [go-mysql-org/go-mysql#911]
Affected version: 1.8.0
Latest working version: 1.7.0

# Reproduction Steps
1- mysql server with complex password and caching_sha2_password as default
```yml
services:
  mysql_test:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: "*pl3$#&XiC4Tn*AP13l#OKUY"
      MYSQL_DATABASE: default
      MYSQL_USER: base-user
      MYSQL_PASSWORD: "*pl3$#&XiC4Tn*AP13l#OKUY"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
```

2- 
```go
package main

import "github.com/go-mysql-org/go-mysql/client"

func main() {
	conn, err := client.Connect("127.0.0.1:3306", "root", "*pl3$#&XiC4Tn*AP13l#OKUY", "default")
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	_, err = conn.Execute(`select 1;`)

	if err != nil {
		panic(err)
	}

	println("connected")
}
```

then you will see this error:
```
panic: handleAuthResult: ERROR 1045 (28000): Access denied for user 'root'@'172.23.0.1' (using password: YES)
```
